name: Daily Job ☞ simple
on:
  # 自动定时更新（每天2点、11点）
  schedule:
    - cron: '0 2,11 * * *'
  # 手动触发更新（点击即运行）
  workflow_dispatch:

jobs:
  force-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须有写权限

    steps:
    - name: 拉取仓库代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 拉取完整历史，避免冲突

    - name: 安装Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 准备目录（确保依赖文件存在）
      run: |
        mkdir -p assets/simple
        touch assets/simple/raw_sources.txt 
        touch assets/simple/simple_rename.txt 

    - name: 运行脚本（强制生成新内容）
      run: python3 assets/simple/simple.py  # 脚本会输出到同目录

    - name: 强制推送（手动/自动触发均生效）
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action Bot"
        git add assets/simple/  # 只提交 assets/simple/ 目录的变化
        git commit -m "${{ github.event_name == 'workflow_dispatch' && '手动触发更新' || '自动定时更新' }} $(date '+%Y-%m-%d %H:%M:%S')" || git commit --allow-empty -m "无内容变更但强制提交"
        git push origin ${{ github.ref_name }} --force  # 强制推送到仓库
